### ISSUE TITLE
Test only

### ISSUE THREAD

**Issue by mrcroc** [dennisreimann/ioctocat#181]
Test prior to real submission

**Comment by dennisreimann** [comment]
test

**Comment by dennisreimann** [comment]
Another test

**Comment by aharren** [comment]
:)

**Comment by aharren** [comment]
hmm. after posting a comment it doesn't show up directly when returning to the issue.

**Comment by aharren** [comment]
...

**Comment by aharren** [comment]
.....................

**Comment by mrcroc** [comment]
Sorry guys, I was just wondering whether iOctocat (a very nice app, BTW)  let me create issues anonymously, when the GitHub portal does not. Forgot that is already knew my Profile. Issue now solved/closed from my perspective :)

**Comment by dennisreimann** [comment]
Sorry that we are abusing this for testing purposes. One more test though ;)

**Comment by aharren** [comment]
ok :)

**Comment by aharren** [comment]
Dennis, somehow it worked now.

**Comment by aharren** [comment]
Urks. Now the text is missing.

**Comment by dennisreimann** [comment]
@aharren I fixed it with this commit: https://github.com/dennisreimann/ioctocat/commit/a02ce027896e5137acd177fcccf532d17f650720

The observer got removed when the view disappeared and reattached when it reappeared. That should work in some but not all cases. The way it is now it should also work, even if the comments are reloaded before the view reappears.

**Comment by aharren** [comment]
OK, I'll try it.

**Comment by dennisreimann** [comment]
It would be nice if you could test the app, because I switched to ARC this morning which was also a big change.

**Comment by mrcroc** [comment]
@dennisreimann on a more serious note, would you mind if I reuse the iOctocat Feedback feature in (one of) my apps? (It's currently closed-source with planned migration to mixed-source.) A first look into the code base suggests that it's feasible (perhaps I would only have to add localization). The license would seem to allow for it, although I want to respect the author's tacit wishes as well, if applicable. (Would also lead to further testing :)

**Comment by aharren** [comment]
@dennisreimann that fix doesn't fix it, it only works the first time; a second comment doesn't show up

btw: going back to the account selection page and re-selecting my account crashes the app (bad observer, bad address)

**Comment by dennisreimann** [comment]
@aharren that must be related to the ARC switch. Let's open a separate issue for that ;)

**Comment by dennisreimann** [comment]
@mrcroc you could reuse it, but I think you'll have to pull in some code for that, because it isn't some modular piece of the app, but just an issues list like used in the rest of the app.

**Comment by mrcroc** [comment]
@dennisreimann thank you very much. Understood & I may give it a try. Pls let me know if you want me to rename this issue so that others interested in reuse may benefit as well :)

**Comment by aharren** [comment]
@dennisreimann here we go: #183
